### ISSUE TITLE
New Logo.

### ISSUE THREAD

**Issue by mendezand** [SandraKuzmic/Tasky#1]
Hi.
I can work on a logo if you wish. I will be attentive if you request it.

Greetings.

**Comment by SandraZiv** [comment]
Hi, 

If you are still interested I will be more than happy to accept your offer. Just keep in mind that Tasky is my side project and if you decide to work on the logo it will be on your free will (ie I can't pay you), but your attribution will be well noticed.
Contact me on mail (kuzmic.sandra1@gmail.com) if you would like to discuss about the terms above.

Best regards,
Sandra
